// Code generated by gopkg.in/reform.v1. DO NOT EDIT.

package models

import (
	"fmt"
	"strings"

	"gopkg.in/reform.v1"
	"gopkg.in/reform.v1/parse"
)

type news_dbTableType struct {
	s parse.StructInfo
	z []interface{}
}

// Schema returns a schema name in SQL database ("").
func (v *news_dbTableType) Schema() string {
	return v.s.SQLSchema
}

// Name returns a view or table name in SQL database ("people").
func (v *news_dbTableType) Name() string {
	return v.s.SQLName
}

// Columns returns a new slice of column names for that view or table in SQL database.
func (v *news_dbTableType) Columns() []string {
	return []string{
		"id",
		"title",
		"content",
	}
}

// NewStruct makes a new struct for that view or table.
func (v *news_dbTableType) NewStruct() reform.Struct {
	return new(News_db)
}

// NewRecord makes a new record for that table.
func (v *news_dbTableType) NewRecord() reform.Record {
	return new(News_db)
}

// PKColumnIndex returns an index of primary key column for that table in SQL database.
func (v *news_dbTableType) PKColumnIndex() uint {
	return uint(v.s.PKFieldIndex)
}

// News_dbTable represents people view or table in SQL database.
var News_dbTable = &news_dbTableType{
	s: parse.StructInfo{
		Type:    "News_db",
		SQLName: "people",
		Fields: []parse.FieldInfo{
			{Name: "Id", Type: "int64", Column: "id"},
			{Name: "Title", Type: "string", Column: "title"},
			{Name: "Content", Type: "string", Column: "content"},
		},
		PKFieldIndex: 0,
	},
	z: new(News_db).Values(),
}

// String returns a string representation of this struct or record.
func (s News_db) String() string {
	res := make([]string, 3)
	res[0] = "Id: " + reform.Inspect(s.Id, true)
	res[1] = "Title: " + reform.Inspect(s.Title, true)
	res[2] = "Content: " + reform.Inspect(s.Content, true)
	return strings.Join(res, ", ")
}

// Values returns a slice of struct or record field values.
// Returned interface{} values are never untyped nils.
func (s *News_db) Values() []interface{} {
	return []interface{}{
		s.Id,
		s.Title,
		s.Content,
	}
}

// Pointers returns a slice of pointers to struct or record fields.
// Returned interface{} values are never untyped nils.
func (s *News_db) Pointers() []interface{} {
	return []interface{}{
		&s.Id,
		&s.Title,
		&s.Content,
	}
}

// View returns View object for that struct.
func (s *News_db) View() reform.View {
	return News_dbTable
}

// Table returns Table object for that record.
func (s *News_db) Table() reform.Table {
	return News_dbTable
}

// PKValue returns a value of primary key for that record.
// Returned interface{} value is never untyped nil.
func (s *News_db) PKValue() interface{} {
	return s.Id
}

// PKPointer returns a pointer to primary key field for that record.
// Returned interface{} value is never untyped nil.
func (s *News_db) PKPointer() interface{} {
	return &s.Id
}

// HasPK returns true if record has non-zero primary key set, false otherwise.
func (s *News_db) HasPK() bool {
	return s.Id != News_dbTable.z[News_dbTable.s.PKFieldIndex]
}

// SetPK sets record primary key, if possible.
//
// Deprecated: prefer direct field assignment where possible: s.Id = pk.
func (s *News_db) SetPK(pk interface{}) {
	reform.SetPK(s, pk)
}

// check interfaces
var (
	_ reform.View   = News_dbTable
	_ reform.Struct = (*News_db)(nil)
	_ reform.Table  = News_dbTable
	_ reform.Record = (*News_db)(nil)
	_ fmt.Stringer  = (*News_db)(nil)
)

func init() {
	parse.AssertUpToDate(&News_dbTable.s, new(News_db))
}
